# Section 5 Lecture 18: Numpy Arrays

In [1]:
import numpy as np

**np.array**

In [2]:
my_list = [1, 2, 3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [3]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**np.arange**

In [4]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

**np.zeros**

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**np.ones**

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**np.linspace**

In [10]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

**np.eye**

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**np.random**

In [15]:
np.random.rand(5)

array([0.62002192, 0.42221731, 0.25159848, 0.34330686, 0.99263577])

In [16]:
np.random.rand(5, 5)

array([[0.03998848, 0.91519021, 0.76329614, 0.9903468 , 0.09953443],
       [0.49699331, 0.32863028, 0.92524465, 0.94521409, 0.24495189],
       [0.17363634, 0.14182241, 0.98423901, 0.80203153, 0.21886006],
       [0.2415826 , 0.55140069, 0.53153075, 0.53354533, 0.60903152],
       [0.72170418, 0.04282631, 0.2203643 , 0.28366004, 0.26618686]])

In [116]:
np.random.randn(5)

array([-1.01613674, -0.16275749, -0.64298226,  0.84397074,  1.95740038])

In [18]:
np.random.randn(4, 4)

array([[-0.20240968,  0.58506736, -0.96904246,  0.59078424],
       [-1.43633751, -0.86633915,  0.44522425, -0.13164375],
       [-1.29424232, -0.68810989,  0.30353681, -0.5793953 ],
       [-0.29068247, -0.12884649, -0.71064879,  1.02977632]])

In [19]:
np.random.randint(1, 100)

32

In [20]:
np.random.randint(1, 100, 10)

array([58, 64, 20, 73, 29, 36, 81, 46, 89, 34])

**reshape**

In [32]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.shape

(25,)

In [22]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**max min**

In [23]:
arr = np.random.randint(0, 50, 10)
arr

array([31,  8, 12, 14, 36,  2, 28, 14, 29, 14])

In [24]:
arr.max()

36

In [25]:
arr.min()

2

In [26]:
arr.argmax()

4

In [27]:
arr.argmin()

5

**data type**

In [30]:
arr.dtype

dtype('int32')

**short type**

In [31]:
from numpy.random import randint
randint(2, 10)

3

# Section 5 Lecture 20: Numpy Array Indexing

In [34]:
import numpy as np
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[8]

8

In [36]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [39]:
arr[7:]

array([ 7,  8,  9, 10])

In [40]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

**notes: slicing**

In [41]:
# the copy of slice of an array will replace the original array
arr = np.arange(0, 11)
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [42]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [43]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
# To copy, we need to specify the copy method
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [45]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [46]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**2d array selection**

In [48]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
arr_2d[0]

array([ 5, 10, 15])

In [49]:
# double bracket
arr_2d[0][0]

5

In [51]:
# single bracket
arr_2d[0, 0]

5

In [52]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [61]:
arr_2d[1:3, :2]

array([[20, 25],
       [35, 40]])

**conditional selection**

In [62]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [65]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [66]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [67]:
arr[arr < 3]

array([1, 2])

**little exercise**

In [68]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
# grab 3x3 26-48
arr_2d[2:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [72]:
arr_2d[2:, 6:]

array([[26, 27, 28, 29],
       [36, 37, 38, 39],
       [46, 47, 48, 49]])

In [73]:
arr_2d[2:, 6:9]

array([[26, 27, 28],
       [36, 37, 38],
       [46, 47, 48]])

# Section 5 Lecture 21: Numpy Operations

In [74]:
import numpy as np

**array with array**

In [77]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

**array with scalar**

In [80]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [81]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [83]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

**universal array function**

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [85]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [86]:
np.max(arr)

10

In [87]:
arr.max()

10

In [88]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [89]:
np.log(arr)

<ipython-input-89-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])